In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
from matplotlib import pyplot as plt

In [2]:
japan_stock = pd.read_csv("../data/japan_stock.csv", parse_dates=True, index_col="date")
japan_bond = pd.read_csv("../data/japan_bond.csv", parse_dates=True, index_col="date")
world_stock = pd.read_csv("../data/world_stock.csv", parse_dates=True, index_col="date")
world_bond = pd.read_csv("../data/world_bond.csv", parse_dates=True, index_col="date")

In [3]:
japan_stock.describe() 

price         diff         rate
count   3214.000000  3213.000000  3213.000000
mean   12942.336341     2.017740     0.005147
std     3407.146373   182.794252     1.439680
min     7411.000000 -1147.000000   -10.633633
25%     9705.000000   -82.000000    -0.684932
50%    12694.000000     8.000000     0.058984
75%    16122.500000   100.000000     0.798242
max    20244.000000  1236.000000    12.223101

In [4]:
japan_stock.head()

price   diff      rate
date                              
2003-09-30  10078    NaN       NaN
2003-10-01  10192  114.0  1.118524
2003-10-02  10464  272.0  2.599388
2003-10-03  10556   92.0  0.871542
2003-10-06  10576   20.0  0.189107

In [5]:
world_stock.head()

price   diff      rate
date                              
2002-09-05  10184    NaN       NaN
2002-09-06  10100  -84.0 -0.831683
2002-09-09  10281  181.0  1.760529
2002-09-10  10305   24.0  0.232897
2002-09-11  10509  204.0  1.941193

In [6]:
japan_joined = japan_stock.join(japan_bond, lsuffix="_japan_stock", rsuffix="_japan_bond")
world_joined = world_stock.join(world_bond, lsuffix="_world_bond",rsuffix="_world_stock")
joined = japan_joined.join(world_joined)

In [7]:
joined = joined.dropna()

In [8]:
conv = joined[["rate_japan_stock", "rate_japan_bond", "rate_world_stock", "rate_world_bond"]]
conv.head()

rate_japan_stock  rate_japan_bond  rate_world_stock  \
date                                                              
2006-05-16         -2.235238         0.162966          0.010014   
2006-05-17          0.723864         0.213436         -0.250979   
2006-05-18         -1.517889        -0.111925          0.429828   
2006-05-19          0.378038         0.162536          0.694858   
2006-05-22         -1.405622         0.344199          0.690063   

            rate_world_bond  
date                         
2006-05-16        -0.425762  
2006-05-17        -0.651859  
2006-05-18        -1.147741  
2006-05-19        -0.435342  
2006-05-22         0.995569

In [9]:
conv.describe()

rate_japan_stock  rate_japan_bond  rate_world_stock  rate_world_bond
count       2570.000000      2570.000000       2570.000000      2570.000000
mean          -0.012775         0.010011          0.009355         0.001988
std            1.521491         0.144068          0.692152         1.629491
min          -10.633633        -1.184891         -6.046863       -11.610776
25%           -0.753988        -0.060178         -0.295767        -0.644832
50%            0.047653         0.008999          0.032568         0.118035
75%            0.821636         0.084922          0.329448         0.802754
max           12.223101         1.114040          6.187462        12.660701

In [10]:
conv.values[:5]

array([[-2.23523787,  0.16296598,  0.01001402, -0.42576157],
       [ 0.72386377,  0.21343633, -0.25097882, -0.65185901],
       [-1.51788941, -0.11192511,  0.42982807, -1.14774115],
       [ 0.3780378 ,  0.16253555,  0.69485805, -0.43534245],
       [-1.40562249,  0.34419923,  0.69006309,  0.99556851]])

In [11]:
np.cov(conv.values, rowvar=0, bias=1)

array([[ 2.31403286, -0.06889757,  0.50284102,  1.51209387],
       [-0.06889757,  0.02074749, -0.01687427, -0.05566072],
       [ 0.50284102, -0.01687427,  0.47888733,  0.81661821],
       [ 1.51209387, -0.05566072,  0.81661821,  2.65420889]])

In [12]:
np.corrcoef(conv.values, rowvar=0)

array([[ 1.        , -0.31443894,  0.47767142,  0.61013571],
       [-0.31443894,  1.        , -0.16928778, -0.23719114],
       [ 0.47767142, -0.16928778,  1.        ,  0.72432726],
       [ 0.61013571, -0.23719114,  0.72432726,  1.        ]])